### PR TITLE
Update to Swift 4.2, Support iOS 10

### PR DESCRIPTION
**Pull request by AgapovOne**
Updated code, project, README.
Also supported iOS 10

### CODE REVIEW

**Comment by AgapovOne** [comment]
@horitaku46 please have a look here

**Comment by Stmol** [comment]
Hi @AgapovOne , did u tested it? Specially on iOS 10 in landscape mode.

**Comment by horitaku46** [comment]
Hi @AgapovOne ! Sorry for replying so late.
I have so much work to do.
Thank you for pull request!
But UI bug at iOS 10 may not be fixed..
Please check with the sample!

**Comment by AgapovOne** [comment]
I could only test this on simulator for iOS 10. And that version really breaks UI on dismissing image. Will move this back to iOS 11+

**Pull request closed without merging**
